# Generated by Django 6.0.4 on 2026-05-12 20:04

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
