# Generated by Django 6.0.4 on 2026-05-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('rest', 'REST API')], default='python', max_length=20),
        ),
    ]
